#!/usr/bin/env bash

#Bash script that displays: 
#To infinity and beyond indefinitely
#I am invincible!!! when receiving a SIGTERM signal
msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
